-- Timeline table setup and seed data
-- Run this in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS public.timeline_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  step TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  icon_svg TEXT,
  display_order INT NOT NULL DEFAULT 1,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT timeline_entries_step_title_unique UNIQUE (step, title)
);

-- Helpful index for timeline fetches in display order.
CREATE INDEX IF NOT EXISTS timeline_entries_active_order_idx
  ON public.timeline_entries (is_active, display_order);

INSERT INTO public.timeline_entries (step, title, description, icon_svg, display_order, is_active)
VALUES
  (
    'Nov 2025',
    'Marked The Beginning',
    'The origin of SRL, where innovation and research journey began.',
    '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09z" /><path d="m12 15-3-3a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.35 22.35 0 0 1-4 2z" /><path d="M9 12H4s.55-3.03 2-4c1.62-1.08 5 0 5 0" /><path d="M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5" /></svg>',
    1,
    TRUE
  ),
  (
    'Dec 2025',
    'Alumni Connecting Session',
    'An interactive gathering where alumni reconnect, share experiences, and inspire members.',
    '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M7.21 15 2.66 7.14a2 2 0 0 1 .13-2.2L4.4 2.8A2 2 0 0 1 6 2h12a2 2 0 0 1 1.6.8l1.6 2.14a2 2 0 0 1 .14 2.2L16.79 15" /><path d="M11 12 5.12 2.2" /><path d="m13 12 5.88-9.8" /><path d="M8 7h8" /><circle cx="12" cy="17" r="5" /><path d="M12 18v-2h-.5" /></svg>',
    2,
    TRUE
  ),
  (
    'Jan 2026',
    'ImpactThon & InnovAItion',
    'SRL students became finalists in InnovAItion and organized ImpactThon successfully.',
    '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10" /><path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20" /><path d="M2 12h20" /></svg>',
    3,
    TRUE
  ),
  (
    'Feb 2026',
    'Theory & Practice Talk',
    'A research talk focused on connecting academic concepts with real-world applications.',
    '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6" /><path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18" /><path d="M4 22h16" /><path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22" /><path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22" /><path d="M18 2H6v7a6 6 0 0 0 12 0V2Z" /></svg>',
    4,
    TRUE
  )
ON CONFLICT (step, title)
DO UPDATE SET
  description = EXCLUDED.description,
  icon_svg = EXCLUDED.icon_svg,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = NOW();

-- Query for the main website
SELECT id, step, title, description, icon_svg, display_order
FROM public.timeline_entries
WHERE is_active = TRUE
ORDER BY display_order ASC, id ASC;
